firmware:
  image: debian
  stage: build
  before_script:
  - apt update
  - apt install -y gcc-arm-none-eabi make python3 git
  script:
  - make clean
  - make
  - make binall
  - echo $(git branch --show-current)
  artifacts:
    paths:
     - obj_app
     - obj_boot
     - obj_f3_boot
     - obj_hvf3
     - stmbl.dfu
     - f3.bin
     - f3.dfu
     - f4.bin
     - f4.dfu

pages:
  image: 
    name: jakejarvis/hugo-extended:latest
    entrypoint: [""]
  stage: deploy
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  # before_script:
  # - apt update
  # - apt install -y git
  # - wget https://github.com/gohugoio/hugo/releases/download/v0.134.2/hugo_extended_0.134.2_linux-amd64.deb
  # - dpkg -i hugo_extended_0.134.2_linux-amd64.deb
  script:
  - cd docs/stmbldoc/
  - hugo
  - echo "The site will be deployed to $CI_PAGES_URL"
  artifacts:
    paths:
    - public
