#!/usr/bin/env python
import re
import sys
import os

def remove_commented_lines(content):
    # Remove lines that are comments or contain comments
    lines = content.split('\n')
    non_comment_lines = [line for line in lines if not line.strip().startswith('#')]
    return '\n'.join(non_comment_lines)

config = []

for infile in sys.argv[2:]:
    with open(infile) as f:
        content = f.read()
        cleaned_content = remove_commented_lines(content)
        config.append((os.path.splitext(os.path.basename(infile))[0], cleaned_content))

code = open(sys.argv[1], 'w')

code.write("//generated by " + sys.argv[0] + " DO NOT EDIT\n\n")
code.write("#include \"config.h\"\n\n")
code.write("const uint32_t num_of_config_templates = " + str(len(config)) + ";\n\n")

code.write("config_template_t config_templates[] = {\n")

for index, (file_name, content) in enumerate(config):
    code.write("{\n")
    code.write(".name = \"" + file_name + "\",\n")
    code.write(".config = \"\\\n")
    for line in content.splitlines():
        code.write(line + "\\n\\\n")
    code.write("\"\n},\n\n")
code.write("};\n")

code.close()